### ISSUE TITLE
Moving diagonally and then colliding does not continue diagonal movement

### ISSUE THREAD

**Issue by Xevion** [n0remac/game-jam-2020#21]
Moving diagonally and then colliding with a wall, before moving away from the colliding surface will not keep diagonal movement (the vertical portion, in this scenario).

See here:
![2020-04-19_23-20-28](https://user-images.githubusercontent.com/44609630/79713831-97192680-8294-11ea-84b8-958dca9b4bf5.gif)

**Comment by Xevion** [comment]
This bug does not occur for horizontal walls it seems. I only tested it on this vertical wall, so it might be a mistake in the if-statements or something.

**Comment by n0remac** [comment]
somehow change_y is being set to 0. I am worried it is in the collision engine. We might have to change the hitbox somehow.

**Comment by Xevion** [comment]
Closing due to repository inactivity.
